// Biology Vocabulary Data - Extracted from Study Guides
const vocabularyData = [
    // Chapter 1 - The Science of Biology
    { term: "observation", definition: "Process of noticing and describing events or processes in a careful, orderly way", chapter: 1 },
    { term: "inference", definition: "A logical interpretation based on prior knowledge and experience", chapter: 1 },
    { term: "hypothesis", definition: "Possible explanation for a set of observations or possible answer to a scientific question", chapter: 1 },
    { term: "controlled experiment", definition: "Experiment in which only one variable is changed", chapter: 1 },
    { term: "independent variable", definition: "Factor in a controlled experiment that is deliberately changed; also called manipulated variable", chapter: 1 },
    { term: "dependent variable", definition: "Variable that is observed and that changes in response to the independent variable; also called responding variable", chapter: 1 },
    { term: "control group", definition: "Group in an experiment that is exposed to the same conditions as the experimental group except for one independent variable", chapter: 1 },
    { term: "data", definition: "Evidence; information gathered from observations", chapter: 1 },
    { term: "theory", definition: "Well-tested explanation that unifies a broad range of observations and hypotheses, and enables scientists to make accurate predictions about new situations", chapter: 1 },
    { term: "bias", definition: "A particular preference or point of view that is personal, rather than scientific", chapter: 1 },
    { term: "biology", definition: "Scientific study of life", chapter: 1 },
    { term: "sexual reproduction", definition: "Type of reproduction in which cells from two parents unite to form the first cell of a new organism", chapter: 1 },
    { term: "asexual reproduction", definition: "Process of reproduction involving a single parent that results in offspring that are genetically identical to the parent", chapter: 1 },
    { term: "DNA", definition: "Deoxyribonucleic acid; genetic material that organisms inherit from their parents", chapter: 1 },
    { term: "metabolism", definition: "The combination of chemical reactions through which an organism builds up or breaks down materials", chapter: 1 },
    { term: "stimulus", definition: "Signal to which an organism responds", chapter: 1 },
    { term: "homeostasis", definition: "Relatively constant internal, physical, and chemical conditions that organisms maintain", chapter: 1 },
    { term: "evolve", definition: "Change over time", chapter: 1 },

    // Chapter 2 - The Chemistry of Life
    { term: "atom", definition: "The basic unit of matter", chapter: 2 },
    { term: "nucleus", definition: "The center of an atom, which contains the protons and neutrons", chapter: 2 },
    { term: "electron", definition: "Negatively charged particle; constantly moving around the nucleus", chapter: 2 },
    { term: "element", definition: "Pure substance that consists entirely of one type of atom", chapter: 2 },
    { term: "isotope", definition: "One of several forms of a single element, which contains the same number of protons but different numbers of neutrons", chapter: 2 },
    { term: "compound", definition: "Substance formed by the chemical combination of two or more elements in definite proportions", chapter: 2 },
    { term: "ionic bond", definition: "Chemical bond formed when one or more electrons are transferred from one atom to another", chapter: 2 },
    { term: "ion", definition: "Atom that has a positive or negative charge", chapter: 2 },
    { term: "covalent bond", definition: "Type of bond between atoms in which the electrons are shared", chapter: 2 },
    { term: "molecule", definition: "Smallest unit of most compounds that displays all the properties of that compound", chapter: 2 },
    { term: "van der Waals forces", definition: "Weak attraction that develops between oppositely charged regions of nearby molecules", chapter: 2 },
    { term: "hydrogen bond", definition: "Weak attraction between a slightly positive hydrogen atom and another atom that is slightly negative", chapter: 2 },
    { term: "cohesion", definition: "Attraction between molecules of the same substance", chapter: 2 },
    { term: "adhesion", definition: "Force of attraction between different kinds of molecules", chapter: 2 },
    { term: "mixture", definition: "Material composed of two or more elements or compounds that are physically mixed together but not chemically combined", chapter: 2 },
    { term: "solution", definition: "Type of mixture in which all the components are evenly distributed", chapter: 2 },
    { term: "solute", definition: "Substance that is dissolved in a solution", chapter: 2 },
    { term: "solvent", definition: "Dissolving substance in a solution", chapter: 2 },
    { term: "suspension", definition: "Mixture of water and nondissolved material", chapter: 2 },
    { term: "pH scale", definition: "Scale with values from 0 to 14, used to measure the concentration of H+ ions in a solution", chapter: 2 },
    { term: "acid", definition: "A compound that forms hydrogen ions (H+) in solution; a solution with a pH of less than 7", chapter: 2 },
    { term: "base", definition: "A compound that produces hydroxide ions (OH-) in solution; a solution with a pH of more than 7", chapter: 2 },
    { term: "buffer", definition: "A compound that prevents sharp, sudden changes in pH", chapter: 2 },
    { term: "monomer", definition: "Small chemical unit that makes up a polymer", chapter: 2 },
    { term: "polymer", definition: "Molecules composed of many monomers; makes up macromolecules", chapter: 2 },
    { term: "carbohydrate", definition: "Compound made up of carbon, hydrogen, and oxygen atoms; type of nutrient that is the major source of energy for the body", chapter: 2 },
    { term: "lipid", definition: "Macromolecule made mostly from carbon and hydrogen atoms; includes fats, oils, and waxes", chapter: 2 },
    { term: "nucleotide", definition: "Subunit of which nucleic acids are composed; made up of a 5-carbon sugar, a phosphate group, and a nitrogenous base", chapter: 2 },
    { term: "nucleic acid", definition: "Macromolecules containing hydrogen, oxygen, nitrogen, carbon, and phosphorus", chapter: 2 },
    { term: "protein", definition: "Macromolecule that contains carbon, hydrogen, oxygen, and nitrogen; needed by the body for growth and repair", chapter: 2 },
    { term: "amino acid", definition: "Compound with an amino group on one end and a carboxyl group on the other end", chapter: 2 },
    { term: "chemical reaction", definition: "Process that changes, or transforms, one set of chemicals into another set of chemicals", chapter: 2 },
    { term: "reactant", definition: "Elements or compounds that enter into a chemical reaction", chapter: 2 },
    { term: "product", definition: "Elements or compounds produced by a chemical reaction", chapter: 2 },
    { term: "activation energy", definition: "Energy that is needed to get a reaction started", chapter: 2 },
    { term: "catalyst", definition: "Substance that speeds up the rate of a chemical reaction", chapter: 2 },
    { term: "enzyme", definition: "Protein catalyst that speeds up the rate of specific biological reactions", chapter: 2 },
    { term: "substrate", definition: "Reactant of an enzyme-catalyzed reaction", chapter: 2 },

    // Chapter 3 - The Biosphere
    { term: "biosphere", definition: "Part of Earth in which life exists including land, water, and air or atmosphere", chapter: 3 },
    { term: "ecology", definition: "Scientific study of interactions among organisms and between organisms and their environment", chapter: 3 },
    { term: "species", definition: "A group of similar organisms that can breed and produce fertile offspring", chapter: 3 },
    { term: "population", definition: "Group of individuals of the same species that live in the same area", chapter: 3 },
    { term: "community", definition: "Assemblage of different populations that live together in a defined area", chapter: 3 },
    { term: "ecosystem", definition: "All the organisms that live in a place, together with their nonliving environment", chapter: 3 },
    { term: "biotic factor", definition: "Any living part of the environment with which an organism might interact", chapter: 3 },
    { term: "abiotic factor", definition: "Physical, or nonliving, factor that shapes an ecosystem", chapter: 3 },
    { term: "atmosphere", definition: "Relatively thin layer of gases that form Earth's outermost layer", chapter: 3 },
    { term: "hydrosphere", definition: "Portion of Earth that consists of water in any of its forms, including oceans, glaciers, rivers, lakes, groundwater, and water vapor", chapter: 3 },
    { term: "geosphere", definition: "The densest parts of Earth, which includes the crust, mantle, and core", chapter: 3 },
    { term: "climate", definition: "Average year-to-year conditions of temperature and precipitation in an area over a long period of time", chapter: 3 },
    { term: "weather", definition: "Day-to-day conditions of the atmosphere, including temperature, precipitation, and other factors", chapter: 3 },
    { term: "greenhouse effect", definition: "The process in which certain gases trap sunlight energy in Earth's atmosphere as heat", chapter: 3 },
    { term: "biome", definition: "A group of ecosystems that share similar climates and typical organisms", chapter: 3 },
    { term: "canopy", definition: "Dense covering formed by the leafy tops of tall rain forest trees", chapter: 3 },
    { term: "understory", definition: "Layer in a rain forest found underneath the canopy formed by shorter trees and vines", chapter: 3 },
    { term: "humus", definition: "Material formed from decaying leaves and other organic matter", chapter: 3 },
    { term: "taiga", definition: "Biome with long cold winters and a few months of warm weather; dominated by coniferous evergreens; also called boreal forest", chapter: 3 },
    { term: "permafrost", definition: "Layer of permanently frozen subsoil found in the tundra", chapter: 3 },
    { term: "photic zone", definition: "Sunlit region near the surface of water", chapter: 3 },
    { term: "aphotic zone", definition: "Dark layer of the oceans below the photic zone where sunlight does not penetrate", chapter: 3 },
    { term: "plankton", definition: "Microscopic organisms that live in aquatic environments; includes both phytoplankton and zooplankton", chapter: 3 },
    { term: "wetland", definition: "Ecosystem in which water either covers the soil or is present at or near the surface for at least part of the year", chapter: 3 },
    { term: "estuary", definition: "Kind of wetland formed where a river meets the ocean", chapter: 3 },

    // Chapter 4 - Ecosystems
    { term: "autotroph", definition: "Organism that is able to capture energy from sunlight or chemicals and use it to produce its own food from inorganic compounds; also called a producer", chapter: 4 },
    { term: "primary producer", definition: "First producer of energy-rich compounds that are later used by other organisms", chapter: 4 },
    { term: "photosynthesis", definition: "Process used by plants and other autotrophs to capture light energy and use it to power chemical reactions that convert carbon dioxide and water into oxygen and energy-rich carbohydrates", chapter: 4 },
    { term: "chemosynthesis", definition: "Process in which chemical energy is used to produce carbohydrates", chapter: 4 },
    { term: "heterotroph", definition: "Organism that obtains food by consuming other living things; also called a consumer", chapter: 4 },
    { term: "consumer", definition: "Organism that relies on other organisms for its energy and food supply; also called a heterotroph", chapter: 4 },
    { term: "detritus", definition: "Small pieces of dead or decaying plant or animal remains", chapter: 4 },
    { term: "food chain", definition: "A series of steps in an ecosystem in which organisms transfer energy by eating and being eaten", chapter: 4 },
    { term: "phytoplankton", definition: "Photosynthetic algae found near the surface of the ocean", chapter: 4 },
    { term: "food web", definition: "Network of complex interactions formed by the feeding relationships among the various organisms in an ecosystem", chapter: 4 },
    { term: "trophic level", definition: "Each step in a food chain or food web", chapter: 4 },
    { term: "ecological pyramid", definition: "Illustration of the relative amounts of energy or matter contained within each trophic level in a food chain or food web", chapter: 4 },
    { term: "biomass", definition: "The total mass of living tissue within a trophic level", chapter: 4 },
    { term: "biogeochemical cycle", definition: "Process in which elements, chemical compounds, and other forms of matter are passed from one organism to another and from one part of the biosphere to another", chapter: 4 },
    { term: "nutrient", definition: "Chemical substance that an organism needs to sustain life", chapter: 4 },
    { term: "nitrogen fixation", definition: "Process of converting nitrogen gas into nitrogen compounds that plants can absorb and use", chapter: 4 },
    { term: "denitrification", definition: "Process by which soil bacteria convert nitrates into nitrogen gas", chapter: 4 },
    { term: "limiting nutrient", definition: "Single essential nutrient that limits productivity in an ecosystem", chapter: 4 },

    // Chapter 5 - Populations
    { term: "population density", definition: "Number of individuals per unit area", chapter: 5 },
    { term: "population distribution", definition: "How individuals are spaced out across their range", chapter: 5 },
    { term: "age structure", definition: "The number of males and females of each age in a population", chapter: 5 },
    { term: "immigration", definition: "Movement of individuals into an area occupied by an existing population", chapter: 5 },
    { term: "emigration", definition: "Movement of individuals out of an area", chapter: 5 },
    { term: "exponential growth", definition: "Growth pattern in which the individuals in a population reproduce at an increasing rate", chapter: 5 },
    { term: "logistic growth", definition: "Growth pattern in which a population's growth slows and then stops following a period of exponential growth", chapter: 5 },
    { term: "carrying capacity", definition: "Largest number of individuals of a particular species that a particular environment can support", chapter: 5 },
    { term: "limiting factor", definition: "Factor that causes population growth to decrease", chapter: 5 },
    { term: "density-dependent limiting factor", definition: "Limiting factor that depends on population density", chapter: 5 },
    { term: "density-independent limiting factor", definition: "Limiting factor that affects all populations in similar ways, regardless of the population density", chapter: 5 }
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = vocabularyData;
}
